services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cars-backend
    ports:
      - "8080:8080"
    networks:
      - cars-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: cars-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - cars-network

networks:
  cars-network:
    driver: bridge
